org: passoz
app: e-core-challenge-passoz
service: e-core-challenge-passoz
frameworkVersion: '3'

custom:
  tableName: 'e-core-challenge-passoz-images-${sls:stage}'
  
provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:PartiQLSelect
          Resource:
            - Fn::GetAtt: [ ImagesTable, Arn ]
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:ListObject
            - s3:PutObject
            - s3:DeleteObject
          Resource: "arn:aws:s3:::e-core-challenge-passoz-images/*"
  environment:
    IMAGES_TABLE: ${self:custom.tableName}

functions:
  getMetadata:
    handler: handlers/getMetadata.handler
    events:
      - httpApi:
          method: GET
          path: '/GetMetadata/{filename}'
  infoImages:
    handler: handlers/infoImages.handler
    events:
      - httpApi: 
          method: GET
          path: '/InfoImages'
  getImage:
    handler: handlers/getImage.handler
    events:
      - httpApi: 
          method: GET
          path: '/GetImage/{filename}'
  extractMetadata:
    handler: handlers/extractMetadata.handler
    events:
      - s3: 
          bucket: e-core-challenge-passoz-images
          event: s3:ObjectCreated:*

resources:
  Resources:
    ImagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: filename
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: filename
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
